### ISSUE TITLE
Unable to run "flatpak-builder" command in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by andsoitgoes** [rlac/flatpak-uqm-megamod#1]
Hi!

Just trying to get Flatpak installed and running on my ubuntu desktop, and I'm DYING to play UQM with all the goodness that lies therein, but I'm struggling to do the Flatpak build I saw you mention on the Serosis github.

Here's the error I get when I've cloned the git and try to run the command, note that when I try to reinstall the FreeDesktop SDK, I get this error:

`sudo flatpak install flathub org.freedesktop.Sdk//18.08
Skipping: org.freedesktop.Sdk/x86_64/18.08 is already installed
`

When I then try to run the builder command, I get this:

`sudo flatpak-builder --install --user builddir com.github.serosis.UQM_MegaMod.json --force-clean
error: org.freedesktop.Platform/x86_64/18.08 not installed
Failed to init: Unable to find runtime org.freedesktop.Platform version 18.08
`

Would love any help, really hoping to get this going this weekend!

Thanks!

**Comment by rlac** [comment]
Sorry, I haven't had enough time to get back to finish the packaging.

The configuration I've put together might incorrectly combine the content (https://github.com/Serosis/UQM-MegaMod/issues/15). I need to look at the source and see what I can do to allow the content to be installed manually by users (or at other possible solutions). For now you can control the content included by editing the .json build file (see lines 125-182 for the content that's included and remove what you don't want).

See if installing the Runtime as well works to build (not sure why it wouldn't be installed if you've got the Sdk though).

`sudo flatpak install flathub org.freedesktop.Runtime//18.08`

**Comment by rlac** [comment]
The build instructions have been updated. If you still have issues building with the latest build files and instructions, please re-open.
