### ISSUE TITLE
Fails to compile due to changes in Serosis' repository.

### ISSUE THREAD

**Issue by mz1193** [rlac/flatpak-uqm-megamod#2]
Hey, just letting you know that this no longer works as the source repository it pulls from has been changed quite a bit.

**Comment by rlac** [comment]
Thanks. It looks like the original repository has been renamed (to https://github.com/Serosis/UQM-MegaMod-Archived) and a new one has taken its place.

I tried updating the build files to use the Archived repository instead, but that didn't work, and I haven't had a chance to look further yet.

I may see if I can update it to use the new repository if it's stable (doesn't look like any releases have been tagged for it yet though).

**Comment by rlac** [comment]
I've updated the build file to point to the renamed repo, so it's building again. It's now pointing to a slightly newer version, and the 19.08 Freedesktop SDK & runtime.

**Comment by mz1193** [comment]
Thank you for looking into it!
