### ISSUE TITLE
Movement controls in combat don't seem to register

### ISSUE THREAD

**Issue by mz1193** [rlac/flatpak-uqm-megamod#3]
No matter how I configure the settings for controls, I can't seem to be able to move in combat. I can, however, fire, and movement works fine when not in combat. This bug also affects Super Melee Mode.

If it's relevant, I'm on Linux Mint 20 and I installed the latest version pointing to the latest repository using the instructions you provided.

**Comment by rlac** [comment]
I've replicated the issue - the latest revision was a quick fix made when UQM-MegaMod's repository was moved, and wasn't tested very well.

0.8.0.85 has recently been released, so I've updated to use this release. I've only done some brief testing but it looks like it's working now. Note though that the new release isn't compatible with saves from previous versions.

Let me know if this resolves the issue for you.

**Comment by mz1193** [comment]
Seems to be working perfectly after your fix, thank you!
